### ISSUE TITLE
Tests fail on Python 3.13

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.copy#15]
### What I did:

Run the tests using Python 3.13.

### What I expect to happen:

Green tests.

### What actually happened:

```python
Error in test test_subobject_w_post_copy_hook (zope.copy.tests.test_copy.Test_clone.test_subobject_w_post_copy_hook)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
  File "/home/runner/work/zope.copy/zope.copy/src/zope/copy/tests/test_copy.py", line 116, in test_subobject_w_post_copy_hook
    c = self._callFUT(o)
  File "/home/runner/work/zope.copy/zope.copy/src/zope/copy/tests/test_copy.py", line 32, in _callFUT
    return clone(obj)
  File "/home/runner/work/zope.copy/zope.copy/src/zope/copy/__init__.py", line [30](https://github.com/zopefoundation/zope.copy/actions/runs/11474414252/job/31930284882?pr=14#step:6:31), in clone
    pickler.persistent_id = persistent.id
AttributeError: '_pickle.Pickler' object attribute 'persistent_id' is read-only
```

### What version of Python and Zope/Addons I am using:

Using GHA: https://github.com/zopefoundation/zope.copy/actions/runs/11474414252/job/31930284882?pr=14

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-10-22 23:39 -0700:
> ...

Maybe, we should use `zodbpickle.pickle` rather than `pickle`.

**Comment by icemac** [comment]
@d-maurer Thank you for the hint, this magically fixed the issue. Could you please review my changes in #14?
